apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    grafana_dashboard: "1"
data:
  loki.yaml: |
    # Automatically provisioned Loki datasource
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: true
        editable: false
        jsonData:
          maxLines: 2000
          timeout: 60
          manageAlerts: false
          derivedFields: []
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData: {}