# MongoDB ServiceMonitor for Prometheus
# This enables MongoDB monitoring in the Rocket.Chat production dashboard
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-servicemonitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: rocketchat
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: rocketchat
      app.kubernetes.io/name: mongodb
  namespaceSelector:
    matchNames:
      - rocketchat
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
      targetLabel: service_name
      replacement: mongodb-metrics
    - sourceLabels: [__meta_kubernetes_service_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
