apiVersion: v1
kind: Secret
metadata:
  name: oke-observability-auth
  namespace: monitoring
  labels:
    release: monitoring
type: Opaque
stringData:
  username: observability-user
  password: 50JjX+diU6YmAZPl

