apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-09-05T18:07:13Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 77.5.0
      chart: kube-prometheus-stack-77.5.0
      heritage: Helm
      release: monitoring
    name: monitoring-kube-prometheus-prometheus
    namespace: monitoring
    resourceVersion: "1355348"
    uid: 90eb9663-023d-4d44-9b7c-f6ce732a8c4b
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - prometheus
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - monitoring-kube-prometheus-prometheus
            topologyKey: kubernetes.io/hostname
          weight: 100
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: monitoring-kube-prometheus-alertmanager
        namespace: monitoring
        pathPrefix: /
        port: http-web
    ruleSelector:
      matchLabels:
        app.kubernetes.io/name: rocketchat
        release: monitoring

    # Alertmanager configuration
    alertmanagerConfigSelector:
      matchLabels:
        app.kubernetes.io/name: alertmanager
    alertmanagerConfigNamespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: monitoring
    automountServiceAccountToken: true
    enableAdminAPI: false
    enableOTLPReceiver: false
    evaluationInterval: 30s
    externalUrl: http://monitoring-kube-prometheus-prometheus.monitoring:9090
    hostNetwork: false
    image: quay.io/prometheus/prometheus:v3.5.0
    imagePullPolicy: IfNotPresent
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
        - monitoring
        - rocketchat
    podMonitorSelector:
      matchLabels:
        release: monitoring
    portName: http-web
    probeNamespaceSelector: {}
    probeSelector:
      matchLabels:
        release: monitoring
    replicas: 1
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
    retention: 7d
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: monitoring
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector:
      matchLabels:
        release: monitoring
    scrapeInterval: 30s
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    serviceAccountName: monitoring-kube-prometheus-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: monitoring
    shards: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: default
    tsdb:
      outOfOrderTimeWindow: 0s
    version: v3.5.0
    walCompression: true
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-09-05T19:11:39Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Available
    - lastTransitionTime: "2025-09-05T19:11:39Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Reconciled
    paused: false
    replicas: 1
    selector: app.kubernetes.io/instance=monitoring-kube-prometheus-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=monitoring-kube-prometheus-prometheus,prometheus=monitoring-kube-prometheus-prometheus
    shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
    shards: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
