###############################################
# DEPRECATION NOTICE
# This manifest is retained for reference only.
# Do NOT apply manually. PodMonitors are now
# rendered and managed by the monitoring Helm
# release via `prometheus.additionalPodMonitors`
# in `aks/config/helm-values/monitoring-values.yaml`.
#
# Applying this file may cause drift with Helm
# ownership/labels and lead to duplicate targets.
###############################################

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rocketchat-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: rocketchat
    release: monitoring  # Required label for Prometheus to discover this PodMonitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: rocketchat
      app.kubernetes.io/name: rocketchat
  namespaceSelector:
    matchNames:
      - rocketchat
  podMetricsEndpoints:
  # Main Rocket.Chat application metrics on port 9458
  - port: metrics  # This is the port name from the pod spec
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: service_name
      replacement: rocketchat
    - sourceLabels: [__meta_kubernetes_pod_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
  # Microservices metrics on port 9459  
  - port: ms-metrics  # This is the port name from the pod spec
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: service_name
      replacement: rocketchat-microservices
    - sourceLabels: [__meta_kubernetes_pod_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rocketchat-microservices
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: rocketchat
    release: monitoring  # Required label for Prometheus to discover this PodMonitor
spec:
  # Target all microservice pods (account, authorization, ddp-streamer, presence, stream-hub)
  selector:
    matchExpressions:
    - key: app.kubernetes.io/instance
      operator: In
      values: [rocketchat]
    - key: app.kubernetes.io/name
      operator: In
      values: [rocketchat-account, rocketchat-authorization, rocketchat-ddp-streamer, rocketchat-presence, rocketchat-stream-hub]
  namespaceSelector:
    matchNames:
      - rocketchat
  podMetricsEndpoints:
  # Microservices expose metrics on port 9459
  - targetPort: 9459  # Using targetPort since microservices might not have named ports
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: service_name
    - sourceLabels: [__meta_kubernetes_pod_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: mongodb-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: rocketchat
    release: monitoring  # Required label for Prometheus to discover this PodMonitor
spec:
  selector:
    matchLabels:
      app: mongodb  # MongoDB pods use this label
  namespaceSelector:
    matchNames:
      - rocketchat
  podMetricsEndpoints:
  # MongoDB exporter metrics if available
  - targetPort: 9216  # MongoDB exporter port
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app]
      targetLabel: service_name
      replacement: mongodb
    - sourceLabels: [__meta_kubernetes_pod_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
