apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: rocketchat
    release: monitoring  # Critical for Prometheus discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: rocketchat
      app.kubernetes.io/instance: rocketchat
  namespaceSelector:
    matchNames:
      - rocketchat
  endpoints:
  - port: moleculer-metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service_name
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
      targetLabel: app
      replacement: rocketchat
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat-mongodb-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: rocketchat
    release: monitoring  # Critical for Prometheus discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/instance: rocketchat
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames:
      - rocketchat
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service_name
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
      targetLabel: app
      replacement: mongodb
