apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rocketchat-podmonitor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rocketchat
    app.kubernetes.io/instance: rocketchat
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: rocketchat
  namespaceSelector:
    matchNames:
      - rocketchat
  podMetricsEndpoints:
  # MongoDB metrics (if available on port 9216)
  - port: mongodb-metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
      targetLabel: service_name
    - sourceLabels: [__meta_kubernetes_pod_namespace]
      targetLabel: namespace
    metricRelabelings: []
