apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rocketchat-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rocketchat
    release: monitoring
spec:
  groups:
  - name: rocketchat
    rules:
    # Critical Service Availability Alerts
    - alert: RocketChatDown
      expr: avg(up{namespace="rocketchat", pod=~"rocketchat-.*"}) == 0
      for: 5m
      labels:
        severity: critical
        service: rocketchat
      annotations:
        summary: "🚨 Rocket.Chat is down"
        description: "Rocket.Chat has been down for more than 5 minutes. Immediate action required."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    - alert: MongoDBConnectionIssues
      expr: avg(up{namespace="rocketchat", pod=~"mongodb-.*"}) == 0
      for: 5m
      labels:
        severity: critical
        service: mongodb
      annotations:
        summary: "🚨 MongoDB connection issues"
        description: "MongoDB replica set is down. Rocket.Chat will be unavailable."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    # Performance Alerts
    - alert: RocketChatHighCPU
      expr: |
        sum by (pod)(rate(container_cpu_usage_seconds_total{namespace="rocketchat", pod=~"rocketchat-.*", image!=""}[5m]))
          /
        clamp_min(sum by (pod)(kube_pod_container_resource_limits{namespace="rocketchat", resource="cpu", unit="core", pod=~"rocketchat-.*"}), 0.001) > 0.8
      for: 15m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat high CPU usage"
        description: "Rocket.Chat CPU utilization above 80% for 15 minutes. Consider scaling or optimization."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    - alert: RocketChatHighMemory
      expr: |
        sum by(pod)(container_memory_usage_bytes{namespace="rocketchat", pod=~"rocketchat-.*"})
          /
        clamp_min(sum by(pod)(kube_pod_container_resource_limits{namespace="rocketchat", resource="memory", pod=~"rocketchat-.*"}), 1)
          > 0.9
      for: 10m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat high memory usage"
        description: "Rocket.Chat memory usage above 90% of limit for 10 minutes."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    # Stability Alerts
    - alert: RocketChatPodRestarting
      expr: increase(kube_pod_container_status_restarts_total{namespace="rocketchat", pod=~"rocketchat-.*"}[10m]) > 2
      for: 5m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat pod restarting frequently"
        description: "More than 2 restarts in the last 10 minutes. Check logs for issues."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    - alert: RocketChatMicroserviceDown
      expr: avg(up{namespace="rocketchat", pod=~"rocketchat-(account|authorization|ddp-streamer|presence|stream-hub)-.*"}) < 1
      for: 5m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat microservice down"
        description: "One or more Rocket.Chat microservices are not running. May impact functionality."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    # MongoDB Specific Alerts
    - alert: MongoDBHighCPU
      expr: |
        sum by (pod)(rate(container_cpu_usage_seconds_total{namespace="rocketchat", pod=~"mongodb-.*", image!=""}[5m]))
          /
        clamp_min(sum by (pod)(kube_pod_container_resource_limits{namespace="rocketchat", resource="cpu", unit="core", pod=~"mongodb-.*"}), 0.001) > 0.8
      for: 15m
      labels:
        severity: warning
        service: mongodb
      annotations:
        summary: "⚠️ MongoDB high CPU usage"
        description: "MongoDB CPU utilization above 80% for 15 minutes. Database performance may be impacted."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    - alert: MongoDBHighMemory
      expr: |
        sum by(pod)(container_memory_usage_bytes{namespace="rocketchat", pod=~"mongodb-.*"})
          /
        clamp_min(sum by(pod)(kube_pod_container_resource_limits{namespace="rocketchat", resource="memory", pod=~"mongodb-.*"}), 1)
          > 0.9
      for: 10m
      labels:
        severity: warning
        service: mongodb
      annotations:
        summary: "⚠️ MongoDB high memory usage"
        description: "MongoDB memory usage above 90% of limit for 10 minutes."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    # Storage and Capacity Alerts
    - alert: RocketChatStorageUsageHigh
      expr: |
        kubelet_volume_stats_used_bytes{namespace="rocketchat"}
          /
        kubelet_volume_stats_capacity_bytes{namespace="rocketchat"} > 0.85
      for: 15m
      labels:
        severity: warning
        service: storage
      annotations:
        summary: "⚠️ Rocket.Chat storage usage high"
        description: "Persistent volume usage above 85%. Consider cleanup or expansion."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/COST_OPTIMIZATION_GUIDE.md"

    - alert: MongoDBStorageUsageHigh
      expr: |
        kubelet_volume_stats_used_bytes{namespace="rocketchat", persistentvolumeclaim=~"mongodb-.*"}
          /
        kubelet_volume_stats_capacity_bytes{namespace="rocketchat", persistentvolumeclaim=~"mongodb-.*"} > 0.90
      for: 15m
      labels:
        severity: warning
        service: mongodb
      annotations:
        summary: "⚠️ MongoDB storage usage critical"
        description: "MongoDB storage usage above 90%. Database may become read-only."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    # Network and Connectivity Alerts
    - alert: RocketChatIngressDown
      expr: |
        probe_success{namespace="monitoring", service="monitoring-ingress"}
        or
        up{namespace="rocketchat", service="rocketchat-rocketchat"} == 0
      for: 5m
      labels:
        severity: critical
        service: ingress
      annotations:
        summary: "🚨 Rocket.Chat ingress unavailable"
        description: "Rocket.Chat ingress/service is not responding to health checks."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    # Application Performance Alerts (Rocket.Chat Specific)
    - alert: RocketChatHighResponseTime
      expr: |
        histogram_quantile(0.95, rate(rocketchat_http_requests_duration_seconds_bucket{namespace="rocketchat"}[5m])) > 5
      for: 10m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat high response time"
        description: "95th percentile response time above 5 seconds for 10 minutes. Users may experience slow performance."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    - alert: RocketChatLowActiveUsers
      expr: rocketchat_users_active < 1
      for: 30m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat low active users"
        description: "No active users for 30 minutes. May indicate connectivity or application issues."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    - alert: RocketChatMessageRateLow
      expr: rate(rocketchat_messages_total[10m]) < 0.1
      for: 30m
      labels:
        severity: info
        service: rocketchat
      annotations:
        summary: "📊 Rocket.Chat low message activity"
        description: "Message rate below 0.1 messages/minute for 30 minutes. Monitor for reduced engagement."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/MONITORING_SETUP_GUIDE.md"

    # Application Performance Alerts (Rocket.Chat Specific)
    - alert: RocketChatHighMessageVolume
      expr: rate(rocketchat_messages_total[5m]) > 20
      for: 10m
      labels:
        severity: info
        service: rocketchat
      annotations:
        summary: "📈 Rocket.Chat high message volume"
        description: "Message rate above 20 messages/minute for 10 minutes. High user activity detected."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/MONITORING_SETUP_GUIDE.md"

    - alert: RocketChatLowUserEngagement
      expr: rocketchat_users_active < 2
      for: 1h
      labels:
        severity: info
        service: rocketchat
      annotations:
        summary: "📊 Rocket.Chat low user engagement"
        description: "Less than 2 active users for 1 hour. Monitor for reduced activity."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/MONITORING_SETUP_GUIDE.md"

    # Error Detection Alerts (Container-based)
    - alert: RocketChatContainerRestartsHigh
      expr: increase(kube_pod_container_status_restarts_total{namespace="rocketchat", container=~"rocketchat.*"}[10m]) > 3
      for: 5m
      labels:
        severity: critical
        service: rocketchat
      annotations:
        summary: "🚨 Rocket.Chat container frequent restarts"
        description: "Rocket.Chat container restarted more than 3 times in 10 minutes. Application instability."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    - alert: RocketChatOOMKills
      expr: increase(kube_pod_container_status_last_terminated_reason{namespace="rocketchat", reason="OOMKilled"}[5m]) > 0
      for: 1m
      labels:
        severity: critical
        service: rocketchat
      annotations:
        summary: "🚨 Rocket.Chat OOM kill detected"
        description: "Rocket.Chat container killed due to out-of-memory. Immediate memory investigation required."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    # Network and Connectivity Alerts
    - alert: RocketChatNetworkErrors
      expr: |
        increase(kube_pod_container_status_last_terminated_reason{namespace="rocketchat", reason=~"Network|DNS|Timeout"}[5m]) > 0
      for: 5m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat network connectivity issues"
        description: "Network or connectivity errors detected in Rocket.Chat containers."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/TROUBLESHOOTING_GUIDE.md"

    # Performance Degradation Alerts
    - alert: RocketChatSlowResponsePattern
      expr: |
        rate(rocketchat_messages_total[5m]) > 5
        and
        rate(kube_pod_container_status_restarts_total{namespace="rocketchat"}[5m]) > 0.1
      for: 15m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "⚠️ Rocket.Chat performance degradation pattern"
        description: "High message volume with container restarts. Performance bottleneck with instability."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/PERFORMANCE_ANALYSIS.md"

    # Cost Monitoring Alerts
    - alert: HighResourceUtilization
      expr: |
        avg(rate(container_cpu_usage_seconds_total{namespace="rocketchat"}[5m])) > 0.7
        or
        avg(container_memory_usage_bytes{namespace="rocketchat"} / container_spec_memory_limit_bytes{namespace="rocketchat"}) > 0.8
      for: 30m
      labels:
        severity: info
        service: cost
      annotations:
        summary: "💰 High resource utilization detected"
        description: "Resources running at high utilization. Review for cost optimization opportunities."
        runbook_url: "https://github.com/Canepro/rocketchat-k8s-deployment/blob/main/docs/COST_OPTIMIZATION_GUIDE.md"
