# Loki Stack Configuration for Rocket.Chat Logging
# Deployed in loki-stack namespace for centralized logging

loki:
  persistence:
    enabled: true
    size: 50Gi  # Increased from 10Gi for better log retention
    storageClassName: default
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

promtail:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  config:
    clients:
      - url: http://loki-stack:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - docker: {}
        - json:
            expressions:
              level: level
              msg: msg
        - labels:
            level:
        - output:
            source: msg
