# Prometheus Stack Configuration for Azure B2s VM
# Optimized for 2 vCPUs, 4GB RAM

# Prometheus configuration
prometheus:
  prometheusSpec:
    retention: "7d"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "default"  # Azure Premium SSD (managed)
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi  # Increased for AKS
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi

# Grafana configuration
grafana:
  adminPassword: "GrafanaAdmin2024!"  # Production password
  persistence:
    enabled: true
    storageClassName: "default"  # Azure Premium SSD
    size: 5Gi  # Increased for AKS
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'rocketchat'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/rocketchat
  ingress:
    enabled: true
    ingressClassName: nginx  # AKS standard ingress class
    annotations:
      cert-manager.io/cluster-issuer: production-cert-issuer
    hosts:
      - grafana.chat.canepro.me
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.chat.canepro.me
  grafana.ini:
    server:
      root_url: https://grafana.chat.canepro.me

# Alertmanager configuration
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "default"  # Azure Premium SSD
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi  # Increased for AKS
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

# Node Exporter
nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

# Kube State Metrics
kubeStateMetrics:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi
