# Official Rocket.Chat Monitoring Configuration
# Consolidated and cleaned - single source of truth
# Based on: https://docs.rocket.chat/docs/deploy-with-kubernetes

grafana:
  adminPassword: "NewSecurePassword2025!"
  persistence:
    enabled: true
    storageClassName: "default"
    size: 5Gi
  grafana.ini:
    server:
      root_url: https://grafana.chat.canepro.me/
      serve_from_sub_path: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'rocketchat'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/rocketchat

prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "default"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "default"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

kubeStateMetrics:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

ingress:
  enabled: true
  ingressClassName: nginx
  tls: true
  grafana:
    enabled: true
    host: grafana.chat.canepro.me
    path: /
