apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-stack.loki-stack.svc.cluster.local:3100
        access: proxy
        jsonData:
          maxLines: 2000
          timeout: 60
          manageAlerts: false
          derivedFields: []
        secureJsonData: {}