apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rocketchat-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: rocketchat
    release: monitoring
spec:
  groups:
  - name: rocketchat
    rules:
    - alert: RocketChatDown
      expr: avg(up{namespace="rocketchat", pod=~"rocketchat-.*"}) == 0
      for: 5m
      labels:
        severity: critical
        service: rocketchat
      annotations:
        summary: "Rocket.Chat is down"
        description: "Rocket.Chat has been down for more than 5 minutes"

    - alert: RocketChatHighCPU
      expr: |
        sum by (pod)(rate(container_cpu_usage_seconds_total{namespace="rocketchat", pod=~"rocketchat-.*", image!=""}[5m]))
          /
        sum by (pod)(kube_pod_container_resource_limits{namespace="rocketchat", resource="cpu", unit="core", pod=~"rocketchat-.*"}) > 0.8
      for: 15m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "Rocket.Chat high CPU usage"
        description: "Rocket.Chat CPU utilization above 80% for 15 minutes"

    - alert: RocketChatHighMemory
      expr: |
        sum by(pod)(container_memory_usage_bytes{namespace="rocketchat", pod=~"rocketchat-.*"})
          /
        sum by(pod)(kube_pod_container_resource_limits{namespace="rocketchat", resource="memory", pod=~"rocketchat-.*"} > 0)
          > 0.9
      for: 10m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "Rocket.Chat high memory usage"
        description: "Rocket.Chat memory usage above 90% of limit for 10 minutes"

    - alert: RocketChatPodRestarting
      expr: increase(kube_pod_container_status_restarts_total{namespace="rocketchat", pod=~"rocketchat-.*"}[10m]) > 2
      for: 5m
      labels:
        severity: warning
        service: rocketchat
      annotations:
        summary: "Rocket.Chat pod restarting"
        description: "More than 2 restarts in the last 10 minutes"

    - alert: MongoDBConnectionIssues
      expr: avg(up{namespace="rocketchat", pod=~"mongodb-.*"}) == 0
      for: 5m
      labels:
        severity: critical
        service: mongodb
      annotations:
        summary: "MongoDB connection issues"
        description: "MongoDB metrics endpoints down for more than 5 minutes"
