# Monitoring overlay configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
resources:
- ../../base

# Monitoring-specific labels
commonLabels:
  monitoring.rocketchat.io/enabled: "true"
  cost.rocketchat.io/conditional: "true"

# Monitoring-specific annotations
commonAnnotations:
  monitoring.rocketchat.io/stack: "full"
  cost.rocketchat.io/optimized: "false"

# Monitoring resources
resources:
- prometheus-deployment.yaml
- grafana-deployment.yaml
- loki-deployment.yaml
- alertmanager-deployment.yaml
- servicemonitors.yaml
- podmonitors.yaml

# Monitoring patches
patchesStrategicMerge:
- rocketchat-monitoring-patch.yaml
- mongodb-monitoring-patch.yaml

# Monitoring configuration
configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml
- name: grafana-datasources
  files:
  - datasources.yml
- name: loki-config
  files:
  - loki.yml
