# Monitoring patches for Rocket.Chat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  namespace: rocketchat
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: rocketchat
        env:
        - name: MONITORING_ENABLED
          value: "true"
        - name: METRICS_ENABLED
          value: "true"
        - name: PROMETHEUS_PORT
          value: "3000"
        - name: PROMETHEUS_PATH
          value: "/metrics"
        # Monitoring resource requirements
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1536Mi
        # Monitoring probes
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        # Monitoring port
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3000
          name: metrics
          protocol: TCP
