# ServiceMonitors for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat-servicemonitor
  namespace: monitoring
  labels:
    app: rocketchat
    component: monitoring
spec:
  selector:
    matchLabels:
      app: rocketchat
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-servicemonitor
  namespace: monitoring
  labels:
    app: mongodb
    component: monitoring
spec:
  selector:
    matchLabels:
      app: mongodb
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-servicemonitor
  namespace: monitoring
  labels:
    app: prometheus
    component: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus
  endpoints:
  - port: web
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
