# Production overlay configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
resources:
- ../../base

# Production-specific labels
commonLabels:
  environment: production
  tier: production
  cost-center: development

# Production-specific annotations
commonAnnotations:
  monitoring.rocketchat.io/enabled: "true"
  backup.rocketchat.io/retention: "7d"
  cost.rocketchat.io/optimized: "true"

# Production resource patches
patchesStrategicMerge:
- rocketchat-production-patch.yaml
- mongodb-production-patch.yaml

# Production environment variables
configMapGenerator:
- name: rocketchat-config
  literals:
  - NODE_ENV=production
  - ROOT_URL=https://chat.canepro.me
  - MONGO_URL=mongodb://mongodb-0.mongodb-headless.rocketchat.svc.cluster.local:27017,mongodb-1.mongodb-headless.rocketchat.svc.cluster.local:27017,mongodb-2.mongodb-headless.rocketchat.svc.cluster.local:27017/rocketchat?replicaSet=rs0&readPreference=primaryPreferred

# Production secrets (templates)
secretGenerator:
- name: mongodb-auth
  literals:
  - username=rocketchat
  - password=SuperStrongPass!
- name: rocketchat-mongodb-auth
  literals:
  - mongo-url=mongodb://rocketchat:SuperStrongPass!@mongodb-0.mongodb-headless.rocketchat.svc.cluster.local:27017,mongodb-1.mongodb-headless.rocketchat.svc.cluster.local:27017,mongodb-2.mongodb-headless.rocketchat.svc.cluster.local:27017/rocketchat?replicaSet=rs0&readPreference=primaryPreferred
  - mongo-oplog-url=mongodb://rocketchat:SuperStrongPass!@mongodb-0.mongodb-headless.rocketchat.svc.cluster.local:27017/local?replicaSet=rs0&readPreference=primaryPreferred
