# Production-specific patches for Rocket.Chat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  namespace: rocketchat
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: rocketchat
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1536Mi
        env:
        - name: NODE_ENV
          value: "production"
        - name: ROOT_URL
          value: "https://chat.canepro.me"
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: rocketchat-mongodb-auth
              key: mongo-url
        - name: MONGO_OPLOG_URL
          valueFrom:
            secretKeyRef:
              name: rocketchat-mongodb-auth
              key: mongo-oplog-url
        - name: MONITORING_ENABLED
          value: "true"
        - name: BACKUP_ENABLED
          value: "true"
      # Production-specific security context
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      # Production node affinity
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload
                operator: In
                values:
                - rocketchat
